wheelcircleData 
                    db       $7F, $00                     ; 0degrees: 0 
                    db       $7E, $FD                     ; 1degrees: 1 
                    db       $7E, $FA                     ; 2degrees: 2 
                    db       $7E, $F7                     ; 3degrees: 4 
                    db       $7E, $F4                     ; 4degrees: 5 
                    db       $7E, $F1                     ; 5degrees: 7 
                    db       $7D, $EE                     ; 6degrees: 8 
                    db       $7D, $EB                     ; 7degrees: 9 
                    db       $7C, $E8                     ; 8degrees: 11 
                    db       $7B, $E5                     ; 9degrees: 12 
                    db       $7B, $E2                     ; 10degrees: 14 
                    db       $7A, $DE                     ; 1degrees: 15 
                    db       $79, $DB                     ; 2degrees: 16 
                    db       $78, $D9                     ; 3degrees: 18 
                    db       $77, $D6                     ; 4degrees: 19 
                    db       $76, $D3                     ; 5degrees: 21 
                    db       $75, $D0                     ; 6degrees: 22 
                    db       $74, $CD                     ; 7degrees: 23 
                    db       $72, $CA                     ; 8degrees: 25 
                    db       $71, $C7                     ; 9degrees: 26 
                    db       $6F, $C4                     ; 20degrees: 28 
                    db       $6E, $C2                     ; 1degrees: 29 
                    db       $6C, $BF                     ; 2degrees: 31 
                    db       $6B, $BC                     ; 3degrees: 32 
                    db       $69, $BA                     ; 4degrees: 33 
                    db       $67, $B7                     ; 56degrees: 35 
                    db       $65, $B5                     ; 6degrees: 36 
                    db       $63, $B2                     ; 7degrees: 38 
                    db       $61, $B0                     ; 8degrees: 39 
                    db       $5F, $AD                     ; 9degrees: 40 
                    db       $5D, $AB                     ; 30degrees: 42 
                    db       $5B, $A9                     ; 1degrees: 43 
                    db       $59, $A6                     ; 2degrees: 45 
                    db       $57, $A4                     ; 3degrees: 46 
                    db       $54, $A2                     ; 4degrees: 48 
                    db       $52, $A0                     ; 5degrees: 49 
                    db       $50, $9E                     ; 6degrees: 50 
                    db       $4D, $9C                     ; 7degrees: 52 
                    db       $4B, $9A                     ; 8degrees: 53 
                    db       $48, $98                     ; 9degrees: 55 
                    db       $46, $97                     ; 40degrees: 56 
                    db       $43, $95                     ; 1degrees: 57 
                    db       $40, $93                     ; 2degrees: 59 
                    db       $3E, $92                     ; 3degrees: 60 
                    db       $3B, $90                     ; 4degrees: 62 
                    db       $38, $8F                     ; 5degrees: 63 
                    db       $35, $8D                     ; 6degrees: 64 
                    db       $32, $8C                     ; 7degrees: 66 
                    db       $30, $8B                     ; 8degrees: 67 
                    db       $2D, $8A                     ; 9degrees: 69 
                    db       $2A, $89                     ; 50degrees: 70 
                    db       $27, $88                     ; 1degrees: 72 
                    db       $24, $87                     ; 2degrees: 73 
                    db       $21, $86                     ; 3degrees: 74 
                    db       $1E, $85                     ; 4degrees: 76 
                    db       $1B, $84                     ; 5degrees: 77 
                    db       $18, $84                     ; 6degrees: 79 
                    db       $15, $83                     ; 7degrees: 80 
                    db       $11, $83                     ; 8degrees: 81 
                    db       $0E, $82                     ; 9degrees: 83 
                    db       $0B, $82                     ; 60degrees: 84 
                    db       $08, $82                     ; 1degrees: 86 
                    db       $05, $82                     ; 2degrees: 87 
                    db       $02, $82                     ; 2degrees: 88 
                    db       $00, $82                     ; 3degrees: 90 64 "angle" == 90 degrees
                    db       $FD, $82                     ; 4degrees: 91 
                    db       $F9, $82                     ; 5degrees: 93 
                    db       $F6, $82                     ; 6degrees: 94 
                    db       $F3, $82                     ; 7degrees: 95 
                    db       $F0, $83                     ; 8degrees: 97 
                    db       $ED, $83                     ; 9degrees: 98 
                    db       $EA, $84                     ; 70degrees: 100 
                    db       $E7, $84                     ; 1degrees: 101 
                    db       $E4, $85                     ; 2degrees: 103 
                    db       $E1, $86                     ; 3degrees: 104 
                    db       $DE, $86                     ; 4degrees: 105 
                    db       $DB, $87                     ; 5degrees: 107 
                    db       $D8, $88                     ; 6degrees: 108 
                    db       $D5, $89                     ; 7degrees: 110 
                    db       $D2, $8A                     ; 8degrees: 111 
                    db       $CF, $8C                     ; 9degrees: 112 
                    db       $CC, $8D                     ; 90degrees: 114 
                    db       $C9, $8E                     ; 1degrees: 115 
                    db       $C6, $90                     ; 2degrees: 117 
                    db       $C4, $91                     ; 3degrees: 118 
                    db       $C1, $93                     ; 4degrees: 119 
                    db       $BE, $94                     ; 5degrees: 121 
                    db       $BC, $96                     ; 6degrees: 122 
                    db       $B9, $98                     ; 7degrees: 124 
                    db       $B6, $99                     ; 8degrees: 125 
                    db       $B4, $9B                     ; 9degrees: 127 
                    db       $B1, $9D                     ; 100degrees: 128 
                    db       $AF, $9F                     ; 1degrees: 129 
                    db       $AD, $A1                     ; 2degrees: 131 
                    db       $AA, $A3                     ; 3degrees: 132 
                    db       $A8, $A5                     ; 4degrees: 134 
                    db       $A6, $A8                     ; 5degrees: 135 
                    db       $A4, $AA                     ; 6degrees: 136 
                    db       $A2, $AC                     ; 7degrees: 138 
                    db       $A0, $AE                     ; 8degrees: 139 
                    db       $9E, $B1                     ; 9degrees: 141 
                    db       $9C, $B3                     ; 110degrees: 142 
                    db       $9A, $B6                     ; 1degrees: 143 
                    db       $98, $B8                     ; 2degrees: 145 
                    db       $96, $BB                     ; 3degrees: 146 
                    db       $95, $BE                     ; 4degrees: 148 
                    db       $93, $C0                     ; 5degrees: 149 
                    db       $91, $C3                     ; 6degrees: 151 
                    db       $90, $C6                     ; 7degrees: 152 
                    db       $8E, $C9                     ; 8degrees: 153 
                    db       $8D, $CB                     ; 9degrees: 155 
                    db       $8C, $CE                     ; 120degrees: 156 
                    db       $8B, $D1                     ; 1degrees: 158 
                    db       $8A, $D4                     ; 2degrees: 159 
                    db       $88, $D7                     ; 3degrees: 160 
                    db       $87, $DA                     ; 4degrees: 162 
                    db       $87, $DD                     ; 5degrees: 163 
                    db       $86, $E0                     ; 6degrees: 165 
                    db       $85, $E3                     ; 7degrees: 166 
                    db       $84, $E6                     ; 8degrees: 167 
                    db       $84, $E9                     ; 9degrees: 169 
                    db       $83, $EC                     ; 130degrees: 170 
                    db       $83, $EF                     ; 1degrees: 172 
                    db       $82, $F2                     ; 2degrees: 173 
                    db       $82, $F6                     ; 3degrees: 175 
                    db       $82, $F9                     ; 4degrees: 176 
                    db       $82, $FC                     ; 5degrees: 177 
                    db       $82, $FF                     ; 6degrees: 179 
                    db       $82, $01                     ; 7degrees: 180 
                    db       $82, $04                     ; 8degrees: 182 
                    db       $82, $07                     ; 9degrees: 183 
                    db       $82, $0A                     ; 140degrees: 184 
                    db       $82, $0E                     ; degrees: 186 
                    db       $83, $11                     ; degrees: 187 
                    db       $83, $14                     ; degrees: 189 
                    db       $84, $17                     ; degrees: 190 
                    db       $84, $1A                     ; degrees: 191 
                    db       $85, $1D                     ; degrees: 193 
                    db       $86, $20                     ; degrees: 194 
                    db       $87, $23                     ; degrees: 196 
                    db       $87, $26                     ; degrees: 197 
                    db       $88, $29                     ; degrees: 199 
                    db       $8A, $2C                     ; degrees: 200 
                    db       $8B, $2F                     ; degrees: 201 
                    db       $8C, $32                     ; degrees: 203 
                    db       $8D, $35                     ; degrees: 204 
                    db       $8E, $37                     ; degrees: 206 
                    db       $90, $3A                     ; degrees: 207 
                    db       $91, $3D                     ; degrees: 208 
                    db       $93, $40                     ; degrees: 210 
                    db       $95, $42                     ; degrees: 211 
                    db       $96, $45                     ; degrees: 213 
                    db       $98, $48                     ; degrees: 214 
                    db       $9A, $4A                     ; degrees: 215 
                    db       $9C, $4D                     ; degrees: 217 
                    db       $9E, $4F                     ; degrees: 218 
                    db       $A0, $52                     ; degrees: 220 
                    db       $A2, $54                     ; degrees: 221 
                    db       $A4, $56                     ; degrees: 223 
                    db       $A6, $58                     ; degrees: 224 
                    db       $A8, $5B                     ; degrees: 225 
                    db       $AA, $5D                     ; degrees: 227 
                    db       $AD, $5F                     ; degrees: 228 
                    db       $AF, $61                     ; degrees: 230 
                    db       $B1, $63                     ; degrees: 231 
                    db       $B4, $65                     ; degrees: 232 
                    db       $B6, $67                     ; degrees: 234 
                    db       $B9, $68                     ; degrees: 235 
                    db       $BC, $6A                     ; degrees: 237 
                    db       $BE, $6C                     ; degrees: 238 
                    db       $C1, $6D                     ; degrees: 239 
                    db       $C4, $6F                     ; degrees: 241 
                    db       $C6, $70                     ; degrees: 242 
                    db       $C9, $72                     ; degrees: 244 
                    db       $CC, $73                     ; degrees: 245 
                    db       $CF, $74                     ; degrees: 247 
                    db       $D2, $76                     ; degrees: 248 
                    db       $D5, $77                     ; degrees: 249 
                    db       $D8, $78                     ; degrees: 251 
                    db       $DB, $79                     ; degrees: 252 
                    db       $DE, $7A                     ; degrees: 254 
                    db       $E1, $7A                     ; degrees: 255 
                    db       $E4, $7B                     ; degrees: 256 
                    db       $E7, $7C                     ; degrees: 258 
                    db       $EA, $7C                     ; degrees: 259 
                    db       $ED, $7D                     ; degrees: 261 
                    db       $F0, $7D                     ; degrees: 262 
                    db       $F3, $7E                     ; degrees: 263 
                    db       $F6, $7E                     ; degrees: 265 
                    db       $F9, $7E                     ; degrees: 266 
                    db       $FD, $7E                     ; degrees: 268 
                    db       $00, $7E                     ; degrees: 269 
                    db       $02, $7E                     ; degrees: 271 
                    db       $05, $7E                     ; degrees: 272 
                    db       $08, $7E                     ; degrees: 273 
                    db       $0B, $7E                     ; degrees: 275 
                    db       $0E, $7E                     ; degrees: 276 
                    db       $11, $7D                     ; degrees: 278 
                    db       $15, $7D                     ; degrees: 279 
                    db       $18, $7C                     ; degrees: 280 
                    db       $1B, $7C                     ; degrees: 282 
                    db       $1E, $7B                     ; degrees: 283 
                    db       $21, $7A                     ; degrees: 285 
                    db       $24, $79                     ; degrees: 286 
                    db       $27, $78                     ; degrees: 287 
                    db       $2A, $77                     ; degrees: 289 
                    db       $2D, $76                     ; degrees: 290 
                    db       $30, $75                     ; degrees: 292 
                    db       $32, $74                     ; degrees: 293 
                    db       $35, $73                     ; degrees: 295 
                    db       $38, $71                     ; degrees: 296 
                    db       $3B, $70                     ; degrees: 297 
                    db       $3E, $6E                     ; degrees: 299 
                    db       $40, $6D                     ; degrees: 300 
                    db       $43, $6B                     ; degrees: 302 
                    db       $46, $69                     ; degrees: 303 
                    db       $48, $68                     ; degrees: 304 
                    db       $4B, $66                     ; degrees: 306 
                    db       $4D, $64                     ; degrees: 307 
                    db       $50, $62                     ; degrees: 309 
                    db       $52, $60                     ; degrees: 310 
                    db       $54, $5E                     ; degrees: 312 
                    db       $57, $5C                     ; degrees: 313 
                    db       $59, $5A                     ; degrees: 314 
                    db       $5B, $57                     ; degrees: 316 
                    db       $5D, $55                     ; degrees: 317 
                    db       $5F, $53                     ; degrees: 319 
                    db       $61, $50                     ; degrees: 320 
                    db       $63, $4E                     ; degrees: 321 
                    db       $65, $4B                     ; degrees: 323 
                    db       $67, $49                     ; degrees: 324 
                    db       $69, $46                     ; degrees: 326 
                    db       $6B, $44                     ; degrees: 327 
                    db       $6C, $41                     ; degrees: 328 
                    db       $6E, $3E                     ; degrees: 330 
                    db       $6F, $3C                     ; degrees: 331 
                    db       $71, $39                     ; degrees: 333 
                    db       $72, $36                     ; degrees: 334 
                    db       $74, $33                     ; degrees: 336 
                    db       $75, $30                     ; degrees: 337 
                    db       $76, $2D                     ; degrees: 338 
                    db       $77, $2A                     ; degrees: 340 
                    db       $78, $27                     ; degrees: 341 
                    db       $79, $25                     ; degrees: 343 
                    db       $7A, $22                     ; degrees: 344 
                    db       $7B, $1E                     ; degrees: 345 
                    db       $7B, $1B                     ; degrees: 347 
                    db       $7C, $18                     ; degrees: 348 
                    db       $7D, $15                     ; degrees: 350 
                    db       $7D, $12                     ; degrees: 351 
                    db       $7E, $0F                     ; degrees: 352 
                    db       $7E, $0C                     ; degrees: 354 
                    db       $7E, $09                     ; degrees: 355 
                    db       $7E, $06                     ; degrees: 357 
                    db       $7E, $03                     ; degrees: 358 
                    db       $7F, $00                     ; degrees: 0 
